"$schema" = 'https://starship.rs/config-schema.json'

# Catppuccin Mocha inspired prompt matching tmux theme
# Soft, elegant, and highly readable

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$ruby\
$rust\
$golang\
$java\
$docker_context\
$kubernetes\
$cmd_duration\
$jobs\
$battery\
$time\
$line_break\
$character"""

# Use Catppuccin Mocha palette
palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
# Catppuccin Mocha colors matching tmux theme
base = "#1e1e2e"
mantle = "#181825"
surface0 = "#313244"
surface1 = "#45475a"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
lavender = "#b4befe"
blue = "#89b4fa"
sapphire = "#74c7ec"
sky = "#89dceb"
teal = "#94e2d5"
green = "#a6e3a1"
yellow = "#f9e2af"
peach = "#fab387"
red = "#f38ba8"
mauve = "#cba6f7"
pink = "#f5c2e7"
overlay0 = "#6c7086"

# Username - more subtle than Tokyo Night
[username]
style_user = "bold fg:sky"
style_root = "bold fg:red"
format = "[$user]($style) "
disabled = false
show_always = false

[hostname]
ssh_only = true
format = "on [$hostname](bold fg:peach) "
disabled = false

[directory]
style = "bold fg:lavender"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncation_symbol = "…/"
read_only = "󰌾"
read_only_style = "fg:red"

[directory.substitutions]
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads"
"Music" = "󰝚 Music"
"Pictures" = " Pictures"
"Videos" = " Videos"
"Desktop" = " Desktop"
"Applications" = " Applications"
"Developer" = "󰲋 Developer"
"Projects" = " Projects"
"Repos" = " Repos"
".config" = " Config"

[git_branch]
symbol = " "
style = "fg:mauve"
format = "[$symbol$branch]($style) "
truncation_length = 35

[git_status]
style = "fg:red"
format = "([$all_status$ahead_behind]($style))"
conflicted = "󰞇 "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "? "
stashed = "󰏗 "
modified = "! "
staged = "+ "
renamed = "» "
deleted = "✘ "

# Language indicators with Catppuccin colors
[nodejs]
symbol = "󰎙 "
style = "fg:green"
format = "[$symbol($version)]($style) "

[python]
symbol = "󰌠 "
style = "fg:yellow"
format = "[$symbol($version)]($style) "

[ruby]
symbol = "󰴭 "
style = "fg:red"
format = "[$symbol($version)]($style) "

[rust]
symbol = "󱘗 "
style = "fg:peach"
format = "[$symbol($version)]($style) "

[golang]
symbol = "󰟓 "
style = "fg:sapphire"
format = "[$symbol($version)]($style) "

[java]
symbol = "󰬷 "
style = "fg:red"
format = "[$symbol($version)]($style) "

[docker_context]
symbol = "󰡨 "
style = "fg:blue"
format = "[$symbol$context]($style) "
only_with_files = true

[kubernetes]
symbol = "󱃾 "
style = "fg:teal"
format = "[$symbol$context( \\($namespace\\))]($style) "
disabled = false

[cmd_duration]
min_time = 2_000
style = "fg:overlay0"
format = "took [$duration]($style) "

[jobs]
symbol = "󰔟 "
style = "fg:yellow"
format = "[$symbol$number]($style) "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "

[[battery.display]]
threshold = 20
style = "fg:red"

[[battery.display]]
threshold = 50
style = "fg:yellow"

[time]
disabled = true
time_format = "%H:%M"
style = "fg:overlay0"
format = "[$time]($style) "

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold fg:green)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:green)"
vimcmd_replace_one_symbol = "[❮](bold fg:mauve)"
vimcmd_replace_symbol = "[❮](bold fg:mauve)"
vimcmd_visual_symbol = "[❮](bold fg:yellow)"